import {
  AlertTriangle,
  ArrowRight,
  Check,
  ChevronLeft,
  ChevronRight,
  Command,
  Database,
  File,
  FileText,
  Globe,
  HelpCircle,
  Image,
  Laptop,
  Loader2,
  Moon,
  MoreVertical,
  Pizza,
  Plus,
  Settings,
  Shield,
  SunMedium,
  Trash,
  Twitter,
  User,
  X,
  Eye,
  EyeOff,
  Search,
  Filter,
  Zap,
  Activity,
  BarChart,
  Bell,
  Bookmark,
  Calendar,
  Cpu,
  Network,
  Radio,
  Lock,
  Users,
  Upload,
  Download,
  List,
} from "lucide-react";

export const Icons = {
  logo: Command,
  close: X,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  settings: Settings,
  user: User,
  plus: Plus,
  arrowRight: ArrowRight,
  help: HelpCircle,
  globe: Globe,
  pizza: Pizza,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  check: Check,
  warning: AlertTriangle,
  database: Database,
  file: File,
  fileText: FileText,
  image: Image,
  more: MoreVertical,
  twitter: Twitter,
  shield: Shield,
  eye: Eye,
  eyeOff: EyeOff,
  search: Search,
  filter: Filter,
  zap: Zap,
  activity: Activity,
  chart: BarChart,
  notification: Bell,
  bookmark: Bookmark,
  calendar: Calendar,
  cpu: Cpu,
  network: Network,
  radio: Radio,
  lock: Lock,
  users: Users,
  upload: Upload,
  download: Download,
  list: List,
};
